### ISSUE TITLE
app速度不太理想

### ISSUE THREAD

**Issue by weimengchao629** [slimkit/thinksns-plus-guide#38]
是服务端框架的瓶颈，还是服务器配置有待提高？

**Comment by Jungle68** [comment]
@weimengchao629  请反馈具体信息，比如说，图片加载慢?动态详情打开较慢等，可以体验一下官方demo。下载地址： https://www.pgyer.com/thinksns-plus-enterprise

**Comment by weimengchao629** [comment]
app打开加载热门微博的时候，时间3-7秒不等

**Comment by Jungle68** [comment]
感谢反馈，已提交技术人员。
